### ISSUE TITLE
レビューのお願い

### ISSUE THREAD

**Issue by muraaano** [Samemura/my-geoplanet#1]
@hiroara @danimal141 
コード完成しました。
PR出そうと思ったら、ブランチしていないとダメだったので、今回はIssueにしました。
コードと、Readmeを見て、コメント頂けると助かります。

https://github.com/Samemura/my-geoplanet/blob/master/README.md
https://github.com/Samemura/my-geoplanet/blob/master/fetch_geoplanet_place.rb
https://github.com/Samemura/my-geoplanet/blob/master/geoplanet.yml

**Comment by hiroara** [comment]
了解しました。ひとまず出せるだけ出していきますね！

**Comment by hiroara** [comment]
見たところ`array_hash`と`tree_hash`にそれぞれplaceを追加していくような形式で、
- `array_hash`: 同階層でのplace羅列用
- `tree_hash`: 親子関係をそのまま表現したツリー型構造用

を意図して設計されたのかなと思いますが、`array_hash`にもツリー構造が出来上がってしまっているように見えます。

結果`File.write`で両方の構造がミックスされたYAMLファイルが出来上がっている感じですね。
`File.write`を1回しか呼んでいないあたりこの辺は意識されていたのかなとも思いますが、どうでしょうか？

**Comment by hiroara** [comment]
Hashにデータを積み上げて最後にファイルに出力する流れになっていますが、このタイプの処理であれば逐次ファイルか標準出力に吐き出していく方が適切かなと思います。
理由として考えているのはメモリ負荷や途中経過が`tail -f`などで見られる、通信エラー時にも最悪途中までのデータが得られる、あたりです。
その場合YAML形式だと吐きづらい(先頭行に`---`が入るなど)があるので、一旦JSONでrawデータとして逐次吐く => 同階層羅列/ツリー構造それぞれのYAML構造にパースするスクリプトで最終出力を出す など複数スクリプトに処理をわけていくのも考えられます。
細かい処理をSTDOUTでつなげていくのはUNIX哲学的でもありますね。途中でJSONを整形なりフィルタするコマンドをかますことも考えられるので拡張性も出てくるかなと。

**Comment by hiroara** [comment]
続いて細かいコーディングレベルで書いていきます！

`$place_num`ですが、スクリプトレベルとはいえやはり可能な限りglobal変数は避けるべきかなと思います。
例えば`get_children_tree`内の`puts`部分を`yield place if block_given?`としておくと、利用箇所でコールバックを渡してロギング用の処理を走らせることができます。ブロックであればクロージャとして変数を参照が可能なのでグローバル変数を避けられます。

**Comment by hiroara** [comment]
それとこれは個人的な設計指針なので好みによる部分もあると思いますが、`array_hash`と`tree_hash`を使って破壊的な変更を行っていくような方式だと可読性やバグ混入が怖いのでimmutableな構造を心がけていたりします。
実際`array_hash`にツリー構造が出来上がっていく現象もこれによるものかなと思っています。
immutableな構造はメモリやデータの生成/破棄処理で多少実行効率が落ちるかなとは思うので、この辺は逐次データを吐き出してく処理方式と併用が良さそうですね。

**Comment by hiroara** [comment]
更に細かい部分については以下に羅列しておきます！
- `23424856`などのマジックナンバーは変数にバインドして適切な名前をつけておく必要があると思います。
  - `type: [7, 8, 9]`なども同様ですね。
- `place_to_yml`で`latitude`を出していますが`longitude`が出ていなさそうです。
  - 抜けかな？とは思いますが、対称性があるのが良さそうです。
- `select: 'long', type: [7, 8, 9], count:0, lang:'ja'`で`:`の後のスペースなど、フォーマットに統一性が取れていない箇所があるみたいです。
- [`if children`の箇所](https://github.com/Samemura/my-geoplanet/blob/40be2d31daab203fc7719c4a2795fe4524b05708/fetch_geoplanet_place.rb#L39)は早期リターンを使って少しインデント深度を下げられそうです。
- `place_to_yml`の命名ですが、YAMLはファイルフォーマットなので`place_to_hash`とかの方が適切そうです。
- あとこちらも僕の好みですが、`GeoPlanet::Place`をラップするクラスを一つ定義してしまうと処理がすっきり書けそうです。

このあたりはRuby的な手法の話も結構混じっていますが、細かいところは以上です！

**Comment by muraaano** [comment]
@hiroara レビューありがとうございました。通知来なくて、気づきませんでした。
改めて指摘いただくと結構ボロボロですね。。。

'tree_hash' と 'array_hash' についてですが、'tree_hash'を作り、オブジェクト参照で'array_hash'を作っています。これで、placeの羅列と親子ツリーをコンパクトに出力してます。
逐次ファイル書き出しだとこれが難しいそうなのと、羅列形式で逐次書き出ししたものを後で、親子ツリーに変換する処理を再度作るほうが手間やメンテに時間がかかるかと思い、この実装にしました。

> if childrenの箇所は早期リターンを使って少しインデント深度を下げられそうです。 

必ず関数の最後に一意でリターンする習慣があったので、参考になります！

> あとこちらも僕の好みですが、GeoPlanet::Placeをラップするクラスを一つ定義してしまうと処理がすっきり書けそうです。

参考になります！

**Comment by hiroara** [comment]
@Samemura なるほど、`tree_hash`と`array_hash`の実装意図は理解しました。
あとはオブジェクト参照を使って配列と木構造が組み合わさったデータを積み上げる処理のメンテナンス性と、データ構造そのものの複雑性あたりを考えた上でトレードオフが成り立つかどうか、、あたりかなと思います。
指摘項目は敢えて好みの部分、Rubyとしてという部分も含めて考えつくところを多めに出しきったという面があるので、ボロボロという話ではないと思って頂けると嬉しいです。
すみません、ありがとうございます！

**Comment by muraaano** [comment]
@hiroara 今更意味ないかもですが、指摘対応しました。
https://github.com/Samemura/my-geoplanet/compare/master@%7B1day%7D...master

結果、結構よくなったと思います。ツリー構造に取得する処理をもう少しよくできるとは思いますが、労力と効果が見合わなそうな感じです。
今回のような建設的で勉強になる指摘をくれる人が周りにいないので、とてもありがたかったです。

そのうち改善できたら、またレビュー依頼だしてしまうかもしれません！
お時間頂いて、ありがとうございました。

**Comment by hiroara** [comment]
@Samemura おお、ご対応ありがとうございます！見通し良くなっていると思います！
また絡めるといいなあと思っていますし、レビューはいくらでも見るので仰ってください。ありがとうございました！

**Comment by muraaano** [comment]
@hiroara お言葉ありがとうございます(^^)
すごく助かります。
ちなみに、今週は現職でやる予定の仕事のサンプル作ってるんですが、Rails 5のActioncable使ってみました。
運用に耐えられるかはあやしいところですが、かなり簡単にSocket使えますね。

良かったら見て下さい。こちらはレビューするものはないですが。
readmeにあるURL2つとも開いて、editのページをサブミットすると動きます。
https://github.com/Samemura/toiletrafic/blob/master/README.md

**Comment by hiroara** [comment]
@Samemura 遅くなりましたが今見てみました！既に実用的な感じですねｗ
ActionCable、コードもシンプルで良い感じですね。まだ全然触っていないので参考になります。
websocketはあんまり扱ったことが無いのでアレですが、同時接続数とかロードバランシングはするのかあたりをクリアにしていけばまあひとまず使えるかなという感覚なので、試す価値ありそうですね！

**Comment by muraaano** [comment]
@hiroara
ありがとうございます。未使用時はRedisでキャッシュされるので、同時接続しても実際に通信してなければ結構いける気がします。サーバーからの一斉送信とかが一番負荷高そうです。
あと、Rails 4.2から5にあげて使ったら、デフォルトのファイルとか足らなくて少しハマりました(^_^;)

また、何かできたら通知させて頂きますね！
